classdef cicFilter
    properties (SetAccess = private)
        Hd;
        G;
    end
    methods
        function obj = cicFilter(decf,diffd,numsecs)
            obj.Hd = dsp.CICDecimator( ...
        'DecimationFactor', decf, ...
        'DifferentialDelay', diffd, ...
        'NumSections', numsecs);
            obj.G = gain(obj.Hd)/decf;
        end
        function y = CIC_LPF(obj,x)
            %CIC_LPF Filters input x and returns output y.

            % MATLAB Code
            % Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
            % Generated on: 01-Jul-2020 15:03:14

            %#codegen

            % To generate C/C++ code from this function use the codegen command.
            % Type 'help codegen' for more information.
            x = x';

            s = fi(x,1,32,16,'RoundingMethod','Round','OverflowAction','Saturate');
            y_fix = step(obj.Hd,s);
            y = (y_fix.data)/obj.G;
        end
    end
end